# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
