# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CatalogoCategorias',
                'verbose_name': 'CatalogoCategoria',
            },
        ),
        migrations.RenameField(
            model_name='entradas',
            old_name='precio',
            new_name='precio_entrada',
        ),
        migrations.RenameField(
            model_name='entradas',
            old_name='tipo',
            new_name='unidad',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='producto',
            new_name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha',
        ),
        migrations.AddField(
            model_name='entradas',
            name='precio_salida',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='upc',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.CatalogoCategoria'),
        ),
    ]
