# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='upc',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
