# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20160615_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
