# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20160615_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='is_active',
        ),
        migrations.AddField(
            model_name='inventario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
