# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20160611_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_entrada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_salida',
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_entrada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_salida',
            field=models.FloatField(default=0),
        ),
    ]
