# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_auto_20160614_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('precio_entrada', models.FloatField(default=0)),
                ('precio_salida', models.FloatField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Producto')),
            ],
            options={
                'verbose_name_plural': 'Entradas',
                'verbose_name': 'Entrada',
            },
        ),
    ]
