# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_auto_20160531_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogocategoria',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_proveedor',
            new_name='nombre',
        ),
    ]
