# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_auto_20160531_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoUnidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CatalogoUnidad',
                'verbose_name_plural': 'Catalogo Unidades',
            },
        ),
    ]
