# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_auto_20160707_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='producto',
        ),
        migrations.AddField(
            model_name='entradas',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.CatalogoCategoria'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entradas',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Proveedor'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.CatalogoUnidades'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='upc',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
