# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_auto_20160711_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='fecha',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
