# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_catalogounidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='unidad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.CatalogoUnidades'),
        ),
    ]
